**2407792**

**BinishaShakya**

 TO-DO-Task
Exercise on Functions:
Task- 1: Create a Python program that converts between different units of measurement.
• The program should:
1. Prompt the user to choose the type of conversion (e.g., length, weight, volume).
2. Ask the user to input the value to be converted.
3. Perform the conversion and display the result.
4. Handle potential errors, such as invalid input or unsupported conversion types.
• Requirements:
1. Functions: Define at least one function to perform the conversion.
2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values).
3. User Input: Prompt the user to select the conversion type and input the value.
4. Docstrings: Include a docstring in your function to describe its purpose, parameters, and return value.
• Conversion
Options:
1. Length:– Convert meters (m) to feet (ft).– Convert feet (ft) to meters (m).
2. Weight:– Convert kilograms (kg) to pounds (lbs).– Convert pounds (lbs) to kilograms (kg).
3. Volume:– Convert liters (L) to gallons (gal).– Convert gallons (gal) to liters (L).

In [3]:
def convert_units(conversion_type, value):
    """
    Convert different units of measurement.

    Parameters:
    conversion_type (int): Selected conversion option.
    value (float): Value to convert.

    Returns:
    float: Converted value.
    """

    if conversion_type == 1:
        return value * 3.28084      # meters to feet
    elif conversion_type == 2:
        return value / 3.28084      # feet to meters
    elif conversion_type == 3:
        return value * 2.20462      # kg to pounds
    elif conversion_type == 4:
        return value / 2.20462      # pounds to kg
    elif conversion_type == 5:
        return value * 0.264172     # liters to gallons
    elif conversion_type == 6:
        return value / 0.264172     # gallons to liters
    else:
        return None


print("Unit Conversion Program")
print("1. Meters to Feet")
print("2. Feet to Meters")
print("3. Kilograms to Pounds")
print("4. Pounds to Kilograms")
print("5. Liters to Gallons")
print("6. Gallons to Liters")

try:
    choice = int(input("Enter your choice (1-6): "))

    if choice < 1 or choice > 6:
        print("Invalid conversion option.")
    else:
        value = float(input("Enter the value to convert: "))
        result = convert_units(choice, value)

        if result is not None:
            # Determine units for display
            if choice == 1:
                unit_from = "meters"
                unit_to = "feet"
            elif choice == 2:
                unit_from = "feet"
                unit_to = "meters"
            elif choice == 3:
                unit_from = "kilograms"
                unit_to = "pounds"
            elif choice == 4:
                unit_from = "pounds"
                unit_to = "kilograms"
            elif choice == 5:
                unit_from = "liters"
                unit_to = "gallons"
            elif choice == 6:
                unit_from = "gallons"
                unit_to = "liters"

            print(f"{value} {unit_from} is equal to {result:.4f} {unit_to}.")
        else:
            print("Conversion not supported.")

except ValueError:
    print("Error: Please enter numeric values only.")

Unit Conversion Program
1. Meters to Feet
2. Feet to Meters
3. Kilograms to Pounds
4. Pounds to Kilograms
5. Liters to Gallons
6. Gallons to Liters
Enter your choice (1-6): 6
Enter the value to convert: 3476
3476.0 gallons is equal to 13158.0940 liters.



Task- 2:
Create a Python program that performs various mathematical operations on a list of numbers. • The Program should:
1. Prompt the user to choose an operation (e.g., find the sum, average, maximum, or minimum of the numbers).
2. Ask the user to input a list of numbers (separated by spaces).
3. Perform the selected operation and display the result.
4. Handle potential errors, such as invalid input or empty lists.

Requirements:
1. Functions: Define at least one function for each operation (sum, average, maximum, minimum).
2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values or empty lists).
3. User Input: Prompt the user to select the operation and input the list of numbers.
4. Docstrings: Include a docstring in each function to describe its purpose, parameters, and return value

In [6]:
def find_sum(numbers):
    """
    Calculates the sum of a list of numbers.

    Parameters:
    numbers (list): A list of numeric values.

    Returns:
    float: The total sum of the numbers.
    """
    return sum(numbers)


def find_average(numbers):
    """
    Calculates the average of a list of numbers.

    Parameters:
    numbers (list): A list of numeric values.

    Returns:
    float: The average value of the numbers.
    """
    return sum(numbers) / len(numbers)


def find_max(numbers):
    """
    Finds the maximum number in a list.

    Parameters:
    numbers (list): A list of numeric values.

    Returns:
    float: The largest number in the list.
    """
    return max(numbers)


def find_min(numbers):
    """
    Finds the minimum number in a list.

    Parameters:
    numbers (list): A list of numeric values.

    Returns:
    float: The smallest number in the list.
    """
    return min(numbers)


def main():
    print("Choose an operation:")
    print("1. Sum")
    print("2. Average")
    print("3. Maximum")
    print("4. Minimum")

    try:
        choice = int(input("Enter your choice (1-4): "))

        user_input = input("Enter numbers separated by spaces: ")
        numbers = [float(num) for num in user_input.split()]

        if len(numbers) == 0:
            raise ValueError("The list cannot be empty.")

        if choice == 1:
            result = find_sum(numbers)
            print("Sum:", result)

        elif choice == 2:
            result = find_average(numbers)
            print("Average:", result)

        elif choice == 3:
            result = find_max(numbers)
            print("Maximum:", result)

        elif choice == 4:
            result = find_min(numbers)
            print("Minimum:", result)

        else:
            print("Invalid choice. Please select between 1 and 4.")

    except ValueError:
        print("Error: Please enter valid numbers and a valid choice.")


if __name__ == "__main__":
    main()

Choose an operation:
1. Sum
2. Average
3. Maximum
4. Minimum
Enter your choice (1-4): 3
Enter numbers separated by spaces: 2
Maximum: 2.0


4.2 Exercise on List Manipulation:
1. Extract Every Other Element: Write a Python function that extracts every other element from a list, starting from the first element.

Requirements:– Define a function extract every other(lst) that takes a list lst as input and returns a new list containing every other element from the original list.

 Example: For the input [1, 2, 3, 4, 5, 6], the output should be [1, 3, 5].

In [7]:
def extract_every_other(lst):
    """
    Extracts every other element from a list starting from the first element.

    Parameters:
    lst (list): The original list of elements.

    Returns:
    list: A new list containing every other element.
    """
    return lst[::2]


# Example usage
numbers = [1, 2, 3, 4, 5, 6]
result = extract_every_other(numbers)

print("Original List:", numbers)
print("Every Other Element:", result)

Original List: [1, 2, 3, 4, 5, 6]
Every Other Element: [1, 3, 5]


2. Slice a Sublist: Write a Python function that returns a sublist from a given list, starting from a specified index and ending at another specified index.

• Requirements:– Define a function get sublist(lst, start, end) that takes a list lst, a starting index start, and an ending index end as input and returns the sublist from start to end (inclusive).

Example: For the input [1, 2, 3, 4, 5, 6] with start=2 and end=4, the output should be [3, 4, 5].

In [8]:
def get_sublist(lst, start, end):
    """
    Returns a sublist from the given list from the start index to the end index (inclusive).

    Parameters:
    lst (list): The original list.
    start (int): Starting index.
    end (int): Ending index.

    Returns:
    list: The extracted sublist.
    """
    return lst[start:end+1]


# Example usage
numbers = [1, 2, 3, 4, 5, 6]
result = get_sublist(numbers, 2, 4)

print("Original List:", numbers)
print("Sublist:", result)

Original List: [1, 2, 3, 4, 5, 6]
Sublist: [3, 4, 5]


3. Reverse a List Using Slicing: Write a Python function that reverses a list using slicing.

•Requirements:– Define a function reverse slicing. list(lst) that takes a list lst and returns a reversed list using

Example: For the input [1, 2, 3, 4, 5], the output should be [5, 4, 3, 2, 1].

In [9]:
def reverse_slicing_list(lst):
    """
    Reverses a list using slicing.

    Parameters:
    lst (list): The original list.

    Returns:
    list: The reversed list.
    """
    return lst[::-1]


# Example usage
numbers = [1, 2, 3, 4, 5]
result = reverse_slicing_list(numbers)

print("Original List:", numbers)
print("Reversed List:", result)

Original List: [1, 2, 3, 4, 5]
Reversed List: [5, 4, 3, 2, 1]


4. Remove the First and Last Elements: Write a Python function that removes the first and last elements of a list and returns the resulting sublist.

• Requirements:
– Define a function remove first last(lst) that takes a list lst and returns a sublist without the first and last elements using slicing.– Example: For the input [1, 2, 3, 4, 5], the output should be [2, 3, 4].

In [10]:

def remove_first_last(lst):
    """
    Removes the first and last elements from a list.

    Parameters:
    lst (list): The original list.

    Returns:
    list: A new list without the first and last elements.
    """
    return lst[1:-1]


# Example usage
numbers = [1, 2, 3, 4, 5]
result = remove_first_last(numbers)

print("Original List:", numbers)
print("Updated List:", result)

Original List: [1, 2, 3, 4, 5]
Updated List: [2, 3, 4]


5. Get the First n Elements: Write a Python function that extracts the first n elements from a list.

 • Requirements:– Define a function get first n(lst, n) that takes a list lst and an integer n as input and returns the first n elements of the list using slicing.– Example: For the input [1, 2, 3, 4, 5] with n=3, the output should be [1, 2, 3].

In [15]:
def get_first_n(numbers, n):
    # Returns the first n elements from a list
    return numbers[:n]


# Example usage
numbers_list = [1, 2, 3, 4, 5]
result = get_first_n(numbers_list, 3)

print("Original List:", numbers_list)
print("First n Elements:", result)

Original List: [1, 2, 3, 4, 5]
First n Elements: [1, 2, 3]


6. Extract Elements from the End: Write a Python function that extracts the last n elements of a list using slicing.

 • Requirements:– Define a function get last n(lst, n) that takes a list lst and an integer n as input and returns the last n elements of the list.– Example: For the input [1, 2, 3, 4, 5] with n=2, the output should be [4, 5].

In [13]:
def get_last_n(lst, n):
    # Returns the last n elements of a list
    return lst[-n:]


# Example usage
numbers = [1, 2, 3, 4, 5]

# We want the last 2 elements
n = 2
result = get_last_n(numbers, n)

print("Original List:", numbers)
print(f"Last {n} Elements:", result)

Original List: [1, 2, 3, 4, 5]
Last 2 Elements: [4, 5]


7. Extract Elements in Reverse Order: Write a Python function that extracts a list of elements in reverse order starting from the second-to-last element and skipping one element in between.

• Requirements:– Define a function reverse skip(lst) that takes a list lst and returns a new list containing every second element starting from the second-to-last, moving backward.– Example: For the input [1, 2, 3, 4, 5, 6], the output should be [5, 3, 1].

In [14]:
def reverse_skip(numbers):
    # Returns every second element starting from the second-to-last, moving backward
    return numbers[-2::-2]


# Example usage
numbers_list = [1, 2, 3, 4, 5, 6]
result = reverse_skip(numbers_list)

print("Original List:", numbers_list)
print("Reverse Skip List:", result)

Original List: [1, 2, 3, 4, 5, 6]
Reverse Skip List: [5, 3, 1]


4.3 Exercise on Nested List:
1. Flatten a Nested List: Write a Python function that takes a nested list and flattens it into a single list, where all the elements are in a single dimension.

 • Requirements:– Define a function flatten(lst) that takes a nested list lst and returns a flattened version of the list.– Example: For the input [[1, 2], [3, 4], [5]], the output should be [1, 2, 3, 4, 5].

In [16]:
def flatten(nested_list):
    # Flattens a nested list into a single list
    flat_list = []
    for sublist in nested_list:
        for item in sublist:
            flat_list.append(item)
    return flat_list


# Example usage
nested_numbers = [[1, 2], [3, 4], [5]]
result = flatten(nested_numbers)

print("Original Nested List:", nested_numbers)
print("Flattened List:", result)

Original Nested List: [[1, 2], [3, 4], [5]]
Flattened List: [1, 2, 3, 4, 5]


2. Accessing Nested List Elements: Write a Python function that extracts a specific element from a nested list given its indices.

 • Requirements:– Define a function access nested element(lst, indices) that takes a nested list lst and a list of indices indices, and returns the element at that position.– Example: For the input lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] with indices = [1, 2], the output should be 6.

In [17]:
def access_nested_element(nested_list, indices):
    # Accesses a nested list element using a list of indices
    element = nested_list
    for index in indices:
        element = element[index]
    return element


# Example usage
nested_numbers = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
indices = [1, 2]  # We want the element at row 1, column 2
result = access_nested_element(nested_numbers, indices)

print("Nested List:", nested_numbers)
print(f"Element at indices {indices}:", result)

Nested List: [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
Element at indices [1, 2]: 6


3. Sum of All Elements in a Nested List: Write a Python function that calculates the sum of all the numbers in a nested list (regardless of depth). • Requirements:– Define a function sum nested(lst) that takes a nested list lst and returns the sum of all the elements.– Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 21.

In [20]:
def sum_nested(nested_numbers):
    # Calculates the sum of all elements in a nested list
    total = 0
    for item in nested_numbers:
        if isinstance(item, list):
            total += sum_nested(item)  # Recursively sum sublists
        else:
            total += item
    return total


# Example usage
nested_list = [[1, 2], [3, [4, 5]], 6]
result = sum_nested(nested_list)

# Input: [[1, 2], [3, [4, 5]], 6]

# First element: [1, 2]

# It’s a list → go inside → sum = 1 + 2 = 3

# Add 3 to total → total = 3

# Second element: [3, [4, 5]]

# It’s a list → go inside

# First number: 3 → add to total = 3 + 3 = 6

# Second element: [4, 5] → it’s a list → go inside → sum = 4 + 5 = 9

# Add 9 to total = 6 + 9 = 15

# Third element: 6

# It’s a number → add 6 → total = 15 + 6 = 21


print("Nested List:", nested_list)
print("Sum of All Elements:", result)

Nested List: [[1, 2], [3, [4, 5]], 6]
Sum of All Elements: 21


4. Remove Specific Element from a Nested List: Write a Python function that removes all occurrences of a specific element from a nested list.

 • Requirements:– Define a function remove element(lst, elem) that removes elem from lst and returns the modified list.– Example: Fortheinput lst = [[1, 2], [3, 2], [4, 5]]andelem = 2,theoutputshould be [[1], [3], [4, 5]].

In [21]:
def remove_element(nested_list, elem):
    # Removes all occurrences of elem from a nested list
    result = []
    for sublist in nested_list:
        # Create a new sublist excluding the element
        new_sublist = [x for x in sublist if x != elem]
        result.append(new_sublist)
    return result


# Example usage
nested_numbers = [[1, 2], [3, 2], [4, 5]]
element_to_remove = 2
result = remove_element(nested_numbers, element_to_remove)

print("Original Nested List:", nested_numbers)
print(f"Nested List after removing {element_to_remove}:", result)

Original Nested List: [[1, 2], [3, 2], [4, 5]]
Nested List after removing 2: [[1], [3], [4, 5]]


5. Find the Maximum Element in a Nested List:

 Write a Python function that finds the maximum element in a nested list (regardless of depth).

 • Requirements:– Define a function find element. max(lst) that takes a nested list lst and returns the maximum– Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 6.

In [22]:
def find_element_max(nested_numbers):
    # Finds the maximum element in a nested list (any depth)
    maximum = float('-inf')  # Start with the smallest possible number
    for item in nested_numbers:
        if isinstance(item, list):
            # Recursively find the max in the sublist
            max_in_sublist = find_element_max(item)
            if max_in_sublist > maximum:
                maximum = max_in_sublist
        else:
            if item > maximum:
                maximum = item
    return maximum


# Example usage
nested_list = [[1, 2], [3, [4, 5]], 6]
result = find_element_max(nested_list)

print("Nested List:", nested_list)
print("Maximum Element:", result)

Nested List: [[1, 2], [3, [4, 5]], 6]
Maximum Element: 6


6. Count Occurrences of an Element in a Nested List:

Write a Python function that counts how many times a specific element appears in a nested list.

•Requirements:– Define a function count occurrences(lst, elem) that counts the occurrences of elem in the nested list lst.– Example: Fortheinput lst = [[1, 2], [2, 3], [2, 4]]andelem = 2,theoutputshould be 3.

In [23]:
def count_occurrences(nested_numbers, elem):
    # Counts how many times elem appears in a nested list
    count = 0
    for item in nested_numbers:
        if isinstance(item, list):
            # Recursively count in the sublist
            count += count_occurrences(item, elem)
        else:
            if item == elem:
                count += 1
    return count


# Example usage
nested_list = [[1, 2], [2, 3], [2, 4]]
element_to_count = 2
result = count_occurrences(nested_list, element_to_count)

print("Nested List:", nested_list)
print(f"Occurrences of {element_to_count}:", result)

Nested List: [[1, 2], [2, 3], [2, 4]]
Occurrences of 2: 3


7. Flatten a List of Lists of Lists:

Write a Python function that flattens a list of lists of lists into a single list, regardless of the depth.

•Requirements:– Define a function deep flatten(lst) that takes a deeply nested list lst and returns a single f lattened list.– Example: For the input [[[1, 2], [3, 4]], [[5, 6], [7, 8]]], the output should be [1, 2, 3, 4, 5, 6, 7, 8].

In [24]:
def deep_flatten(nested_numbers):
    # Flattens a nested list of any depth into a single list
    flat_list = []
    for item in nested_numbers:
        if isinstance(item, list):
            # Recursively flatten the sublist
            flat_list.extend(deep_flatten(item))
        else:
            flat_list.append(item)
    return flat_list


# Example usage
nested_list = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
result = deep_flatten(nested_list)

print("Original Nested List:", nested_list)
print("Flattened List:", result)

Original Nested List: [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
Flattened List: [1, 2, 3, 4, 5, 6, 7, 8]


8. Nested List Average:

Write a Python function that calculates the average of all elements in a nested list.

•Requirements:– Define a function average of all the elements. nested(lst) that takes a nested list lst and returns the average– Example: For the input [[1, 2], [3, 4], [5, 6]], the output should be 3.5.

In [25]:
def average_of_all_nested(nested_numbers):
    # Calculates the average of all elements in a nested list

    # Helper function to sum all elements and count them
    def helper(numbers):
        total = 0
        count = 0
        for item in numbers:
            if isinstance(item, list):
                t, c = helper(item)   # Recursively sum sublists
                total += t
                count += c
            else:
                total += item
                count += 1
        return total, count

    total_sum, total_count = helper(nested_numbers)
    if total_count == 0:
        return 0  # To avoid division by zero
    return total_sum / total_count


# Example usage
nested_list = [[1, 2], [3, 4], [5, 6]]
result = average_of_all_nested(nested_list)

print("Nested List:", nested_list)
print("Average of all elements:", result)

Nested List: [[1, 2], [3, 4], [5, 6]]
Average of all elements: 3.5


10 To- Do- NumPy

Please complete all the problems listed below:
10.1 Basic Vector and Matrix Operation with Numpy.

Problem- 1: Array Creation: Complete the following Tasks:
1. Initialize an empty array with size 2X2.
2. Initialize an all one array with size 4X2.
3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [26]:
import numpy as np

# 1. Initialize an empty array with size 2x2
empty_array = np.empty((2, 2))
print("1. Empty Array (2x2):\n", empty_array, "\n")

# 2. Initialize an all ones array with size 4x2
ones_array = np.ones((4, 2))
print("2. All Ones Array (4x2):\n", ones_array, "\n")

# 3. Return a new array of given shape and type, filled with fill value
# Example: shape (3,3), fill value 7, dtype=int
filled_array = np.full((3, 3), fill_value=7, dtype=int)
print("3. Array filled with 7 (3x3):\n", filled_array, "\n")

# 4. Return a new array of zeros with same shape and type as a given array
example_array = np.array([[5, 6, 7], [8, 9, 10]])
zeros_like_array = np.zeros_like(example_array)
print("4. Zeros like example_array:\n", zeros_like_array, "\n")

# 5. Return a new array of ones with same shape and type as a given array
ones_like_array = np.ones_like(example_array)
print("5. Ones like example_array:\n", ones_like_array, "\n")

# 6. Convert an existing list to a numpy array
new_list = [1, 2, 3, 4]
array_from_list = np.array(new_list)
print("6. Numpy Array from list [1,2,3,4]:\n", array_from_list)

1. Empty Array (2x2):
 [[3.90124607e-315 0.00000000e+000]
 [0.00000000e+000 2.12199579e-314]] 

2. All Ones Array (4x2):
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]] 

3. Array filled with 7 (3x3):
 [[7 7 7]
 [7 7 7]
 [7 7 7]] 

4. Zeros like example_array:
 [[0 0 0]
 [0 0 0]] 

5. Ones like example_array:
 [[1 1 1]
 [1 1 1]] 

6. Numpy Array from list [1,2,3,4]:
 [1 2 3 4]


Problem- 2:

Array Manipulation: Numerical Ranges and Array indexing: Complete the following tasks:
1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
2. Create a 3X3 matrix with values ranging from 0 to 8. {Hint:look for np.reshape()}
3. Create a 3X3 identity matrix.{Hint:np.eye()}
4. Create a random array of size 30 and find the mean of the array. {Hint:check for np.random.random() and array.mean() function}
 5. Create a 10X10 array with random values and find the minimum and maximum values.
 6. Create a zero array of size 10 and replace 5th element with 1.
 7. Reverse an array arr = [1,2,0,0,4,0].
 8. Create a 2d array with 1 on border and 0 inside.
 9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [27]:
import numpy as np

# 1. Create an array with values ranging from 10 to 49
array_10_49 = np.arange(10, 50)
print("1. Array 10 to 49:\n", array_10_49, "\n")

# 2. Create a 3x3 matrix with values ranging from 0 to 8
matrix_3x3 = np.arange(9).reshape(3,3)
print("2. 3x3 Matrix 0-8:\n", matrix_3x3, "\n")

# 3. Create a 3x3 identity matrix
identity_matrix = np.eye(3)
print("3. 3x3 Identity Matrix:\n", identity_matrix, "\n")

# 4. Create a random array of size 30 and find the mean
random_array_30 = np.random.random(30)
mean_random_array = random_array_30.mean()
print("4. Random Array of size 30:\n", random_array_30)
print("   Mean:", mean_random_array, "\n")

# 5. Create a 10x10 array with random values and find min and max
random_array_10x10 = np.random.random((10,10))
min_val = random_array_10x10.min()
max_val = random_array_10x10.max()
print("5. 10x10 Random Array:\n", random_array_10x10)
print("   Min:", min_val, "Max:", max_val, "\n")

# 6. Create a zero array of size 10 and replace 5th element with 1
zero_array_10 = np.zeros(10)
zero_array_10[4] = 1  # index 4 is the 5th element
print("6. Zero Array with 5th element = 1:\n", zero_array_10, "\n")

# 7. Reverse an array arr = [1,2,0,0,4,0]
arr = np.array([1,2,0,0,4,0])
reversed_arr = arr[::-1]
print("7. Reversed Array:\n", reversed_arr, "\n")

# 8. Create a 2D array with 1 on border and 0 inside
size = 5  # example 5x5
border_array = np.ones((size,size))
border_array[1:-1, 1:-1] = 0
print("8. 2D Array with 1 on border, 0 inside:\n", border_array, "\n")

# 9. Create 8x8 checkerboard pattern
checkerboard = np.zeros((8,8))
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("9. 8x8 Checkerboard Pattern:\n", checkerboard)

1. Array 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49] 

2. 3x3 Matrix 0-8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]] 

3. 3x3 Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 

4. Random Array of size 30:
 [0.7843861  0.27392865 0.1163956  0.87181124 0.15637933 0.72584207
 0.1459009  0.47081471 0.72107404 0.60894965 0.70823514 0.21675632
 0.79158236 0.1008587  0.11443489 0.84913565 0.46813973 0.72355011
 0.48099078 0.35521387 0.52070243 0.08376278 0.53102113 0.76140239
 0.55722511 0.5697658  0.20017158 0.82311394 0.35404285 0.3209293 ]
   Mean: 0.4802172380526913 

5. 10x10 Random Array:
 [[0.10976316 0.54743135 0.03095484 0.5468669  0.00512155 0.02555518
  0.62349358 0.50900478 0.51400758 0.80477413]
 [0.2730485  0.33435186 0.94843362 0.96133049 0.31903521 0.84666739
  0.28690634 0.26350431 0.78460671 0.26060612]
 [0.49089736 0.57149593 0.42581169 0.89211256 0.19639574 0.01099882
  0.16369691 0.79323728 

Problem- 3:
 Array Operations: For the following arrays: x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]); v = np.array([9,10]) and w = np.array([11,12]);

 Complete all the task using numpy:
 1. Add the two array.
 2. Subtract the two array.
 3. Multiply the array with any integers of your choice.
 4. Find the square of each element of the array.
 5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
 6. Concatenate x(and)y along row and Concatenate v(and)w along column. {Hint:try np.concatenate() or np.vstack() functions.
 7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [28]:

import numpy as np

# Given arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

print("x:\n", x)
print("y:\n", y)
print("v:", v)
print("w:", w, "\n")

# 1. Add x and y
add_xy = x + y
print("1. x + y:\n", add_xy, "\n")

# 2. Subtract x and y
sub_xy = x - y
print("2. x - y:\n", sub_xy, "\n")

# 3. Multiply the array with an integer (e.g., 3)
mul_x = x * 3
print("3. x * 3:\n", mul_x, "\n")

# 4. Square of each element
square_x = x ** 2
print("4. x squared:\n", square_x, "\n")

# 5. Dot product
dot_vw = np.dot(v, w)  # vectors
dot_xv = np.dot(x, v)  # matrix and vector
dot_xy = np.dot(x, y)  # matrices
print("5a. Dot product of v and w:", dot_vw)
print("5b. Dot product of x and v:\n", dot_xv)
print("5c. Dot product of x and y:\n", dot_xy, "\n")

# 6. Concatenate
concat_row_xy = np.concatenate((x, y), axis=0)  # along rows
concat_col_vw = np.concatenate((v.reshape(-1,1), w.reshape(-1,1)), axis=1)  # along columns
print("6a. Concatenate x and y along rows:\n", concat_row_xy)
print("6b. Concatenate v and w along columns:\n", concat_col_vw, "\n")

# 7. Concatenate x and v (will cause an error)
try:
    concat_xv = np.concatenate((x, v), axis=0)
except ValueError as e:
    print("7. Error when concatenating x and v:", e)
    print("   Explanation: x is 2x2 matrix, v is 1D array of size 2. Shapes do not match for concatenation along axis=0.")

x:
 [[1 2]
 [3 5]]
y:
 [[5 6]
 [7 8]]
v: [ 9 10]
w: [11 12] 

1. x + y:
 [[ 6  8]
 [10 13]] 

2. x - y:
 [[-4 -4]
 [-4 -3]] 

3. x * 3:
 [[ 3  6]
 [ 9 15]] 

4. x squared:
 [[ 1  4]
 [ 9 25]] 

5a. Dot product of v and w: 219
5b. Dot product of x and v:
 [29 77]
5c. Dot product of x and y:
 [[19 22]
 [50 58]] 

6a. Concatenate x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
6b. Concatenate v and w along columns:
 [[ 9 11]
 [10 12]] 

7. Error when concatenating x and v: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
   Explanation: x is 2x2 matrix, v is 1D array of size 2. Shapes do not match for concatenation along axis=0.


Problem- 4: Matrix Operations:

• For the following arrays: A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
Prove following with Numpy:
1. Prove A.A−1 = I.
2. Prove AB̸ = BA.
3. Prove (AB)T = BTAT.

• Solve the following system of Linear equation using Inverse Methods. 2x −3y+z =−1 x −y+2z =−3 3x +y−z =9 {Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}

• Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” function of Numpy}

In [29]:
import numpy as np

# Given matrices
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

print("Matrix A:\n", A)
print("Matrix B:\n", B, "\n")

# 1. Prove A * A^-1 = I
A_inv = np.linalg.inv(A)        # inverse of A
identity = np.dot(A, A_inv)     # multiply A with its inverse
print("1. A * A^-1:\n", identity)
print("   Should be close to identity matrix\n")

# 2. Prove AB ≠ BA
AB = np.dot(A, B)
BA = np.dot(B, A)
print("2. AB:\n", AB)
print("   BA:\n", BA)
print("   AB equals BA? ", np.array_equal(AB, BA), "\n")

# 3. Prove (AB)^T = B^T * A^T
AB_T = (np.dot(A,B)).T
B_T_A_T = np.dot(B.T, A.T)
print("3. (AB)^T:\n", AB_T)
print("   B^T * A^T:\n", B_T_A_T)
print("   Are they equal? ", np.array_equal(AB_T, B_T_A_T), "\n")

# Solve system of linear equations:
# 2x −3y + z = −1
# x − y + 2z = −3
# 3x + y − z = 9

# Represent in matrix form: AX = B
A_sys = np.array([[2, -3, 1],
                  [1, -1, 2],
                  [3, 1, -1]])

B_sys = np.array([-1, -3, 9])

# Solve using np.linalg.inv
A_sys_inv = np.linalg.inv(A_sys)
X = np.dot(A_sys_inv, B_sys)

print("Solution of the system using inverse method:")
print("x =", X[0], "y =", X[1], "z =", X[2])

Matrix A:
 [[3 4]
 [7 8]]
Matrix B:
 [[5 3]
 [2 1]] 

1. A * A^-1:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
   Should be close to identity matrix

2. AB:
 [[23 13]
 [51 29]]
   BA:
 [[36 44]
 [13 16]]
   AB equals BA?  False 

3. (AB)^T:
 [[23 51]
 [13 29]]
   B^T * A^T:
 [[23 51]
 [13 29]]
   Are they equal?  True 

Solution of the system using inverse method:
x = 2.0 y = 1.0 z = -2.0


10.2 Experiment: How Fast is Numpy? In this exercise, you will compare the performance and implementation of operations using plain Python lists (arrays) and NumPy arrays. Follow the instructions:
1. Element-wise Addition: • Using Python Lists, perform element-wise addition of two lists of size 1,000,000. Measure and Print the time taken for this operation.

• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this operation.

2. Element-wise Multiplication • Using Python Lists, perform element-wise multiplication of two lists of size 1,000,000. Measure and Print the time taken for this operation.

• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this operation.

 3. Dot Product • Using Python Lists, compute the dot product of two lists of size 1,000,000. Measure and Print the time taken for this operation.

 • Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this operation. 4. Matrix Multiplication

 • Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Measure and print the time taken for this operation.

 • Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000. Measure and print the time taken for this operation.

In [31]:
import numpy as np
import time

# 1. Element-wise Addition
size = 1_000_000

# Using Python lists
list1 = list(range(size))
list2 = list(range(size))

start_time = time.time()
add_list = [a + b for a, b in zip(list1, list2)]
end_time = time.time()
print("Python list addition time:", end_time - start_time, "seconds")

# Using NumPy arrays
arr1 = np.arange(size)
arr2 = np.arange(size)

start_time = time.time()
add_np = arr1 + arr2
end_time = time.time()
print("NumPy array addition time:", end_time - start_time, "seconds\n")

# 2. Element-wise Multiplication

# Python lists
start_time = time.time()
mul_list = [a * b for a, b in zip(list1, list2)]
end_time = time.time()
print("Python list multiplication time:", end_time - start_time, "seconds")

# NumPy arrays
start_time = time.time()
mul_np = arr1 * arr2
end_time = time.time()
print("NumPy array multiplication time:", end_time - start_time, "seconds\n")

# 3. Dot Product

# Python lists
start_time = time.time()
dot_list = sum(a * b for a, b in zip(list1, list2))
end_time = time.time()
print("Python list dot product time:", end_time - start_time, "seconds")

# NumPy arrays
start_time = time.time()
dot_np = np.dot(arr1, arr2)
end_time = time.time()
print("NumPy array dot product time:", end_time - start_time, "seconds\n")



Python list addition time: 0.08450937271118164 seconds
NumPy array addition time: 0.0037772655487060547 seconds

Python list multiplication time: 0.07689690589904785 seconds
NumPy array multiplication time: 0.004293918609619141 seconds

Python list dot product time: 0.08431196212768555 seconds
NumPy array dot product time: 0.0017077922821044922 seconds



In [32]:
# 4. Matrix Multiplication (1000 x 1000)

size_mat = 1000

# Python lists
matrix1 = [[i+j for j in range(size_mat)] for i in range(size_mat)]
matrix2 = [[i+j for j in range(size_mat)] for i in range(size_mat)]

start_time = time.time()


In [36]:
size_mat = 100  # smaller size for Python loops

# naive matrix multiplication with loops
result_list = [[0]*size_mat for _ in range(size_mat)]
start_time = time.time()
for i in range(size_mat):
    for j in range(size_mat):
        sum_val = 0
        for k in range(size_mat):
            sum_val += matrix1[i][k] * matrix2[k][j]
        result_list[i][j] = sum_val
end_time = time.time()
print("Python list matrix multiplication time (100x100):", end_time - start_time, "seconds")


Python list matrix multiplication time (100x100): 0.227980375289917 seconds


In [35]:
# NumPy arrays
mat1 = np.arange(size_mat*size_mat).reshape(size_mat, size_mat)
mat2 = np.arange(size_mat*size_mat).reshape(size_mat, size_mat)

start_time = time.time()
result_np = np.dot(mat1, mat2)
end_time = time.time()
print("NumPy array matrix multiplication time (1000x1000):", end_time - start_time, "seconds")

NumPy array matrix multiplication time (1000x1000): 1.6306564807891846 seconds
